### ISSUE TITLE
Add linux/arm64/v8 support

### ISSUE THREAD

**Issue by defiways** [criccomini/hive-metastore-standalone#2]
Is it possible to generate a docker image that supports ARM support?

this is what I see trying to run on my M1.

docker pull ghcr.io/recap-build/hive-metastore-standalone:latest --platform linux/arm64

latest: Pulling from recap-build/hive-metastore-standalone
1efc276f4ff9: Pull complete 
a2f2f93da482: Pull complete 
1a2de4cc9431: Pull complete 
9013b84ebbe7: Pull complete 
13a75c41290c: Pull complete 
7e16fa9c54fa: Pull complete 
354596e2e1ce: Pull complete 
61f6fbf5b34e: Pull complete 
Digest: sha256:779bc136cbc7e0959ba19ef85a19a669b466ff228d4e5ecf977d343ac0201cb6
Status: Downloaded newer image for ghcr.io/recap-build/hive-metastore-standalone:latest
image with reference ghcr.io/recap-build/hive-metastore-standalone:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
 % docker run --rm --detach --name hms-standalone \
                --publish 9083:9083 \
                ghcr.io/recap-build/hive-metastore-standalone:latest                      
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2464403a60a62f6c25a8e7703f84e220feaa071a360d53d0fce24e33c5091d60

**Comment by criccomini** [comment]
Sure! Want to submit a PR to add it?
